dremio:
  auth:
    enabled: true
    username: "admin"
    password: "Pa22word"
    firstName: "Josh"
    lastName: "Yorko"
    email: "joshua.yorko@gainwelltechnologies.com"

  masterCoordinator:
    resources:
      requests:
        memory: "48Gi"
        cpu: "4"
      limits:
        memory: "60Gi"
        cpu: "6"
    persistence:
      storageClass: "gp2-expandable"
      size: 50Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    envVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  coordinator:
    resources:
      requests:
        memory: "24Gi"
        cpu: "4"
      limits:
        memory: "48Gi"
        cpu: "6"
    persistence:
      storageClass: "gp2-expandable"
      size: 50Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    envVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password



  executor:
    common:
      replicaCount: 15
      resources:
  
        requests:
          memory: "8Gi"  # 4 GiB memory request per pod
          cpu: "2"       # 2 CPU cores request per pod
        limits:
          memory: "16Gi"  # 8 GiB memory limit per pod
          cpu: "4"       # 4 CPU cores limit per pod
      persistence:
        storageClass: "gp2-expandable"
        size: 20Gi
      extraStartParams: >-
        -Xmx6g                        # Adjusted heap memory to 6 GiB
        -XX:MaxDirectMemorySize=2g    # Adjusted direct memory size to 2 GiB
        -XX:+UseG1GC
        -XX:G1HeapRegionSize=32M
        -XX:+UseGCOverheadLimit
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/opt/dremio/data/heap-dump.hprof
        -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
        -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
      envVars:
        - name: DREMIO_TLS_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dremio-keystore-password
              key: password





  initContainers:
    - name: copy-default-conf
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    - name: generate-conf
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    - name: init-certs
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    - name: set-keystore-permissions
      image: busybox
      command: ['sh', '-c', 'chown -R 1001:1001 /opt/dremio/tls && chmod -R 600 /opt/dremio/tls/*']
      volumeMounts:
        - name: dremio-tls
          mountPath: /opt/dremio/tls
    - name: setup-tls
      image: busybox
      command: ['sh', '-c', 'mkdir -p /opt/dremio/tls && cp /tls-secret/dremio.jks /opt/dremio/tls/dremio.jks && chmod 600 /opt/dremio/tls/dremio.jks && chown 1001:1001 /opt/dremio/tls/dremio.jks']
      volumeMounts:
        - name: dremio-tls
          mountPath: /tls-secret
        - name: tls-dir
          mountPath: /opt/dremio/tls

  service:
    type: LoadBalancer

  extraVolumes:
    - name: dremio-tls
      secret:
        secretName: dremio-tls-secret
    - name: tls-dir
      emptyDir: {}

  extraVolumeMounts:
    - name: dremio-tls
      mountPath: /opt/dremio/tls
      readOnly: true
    - name: tls-dir
      mountPath: /opt/dremio/tls

  extraEnvVars:
    - name: DREMIO_TLS_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dremio-keystore-password
          key: password

minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "Pa22word22"
  defaultBuckets: "dremio,warehouse,upload"
  provisioning:
    enabled: true
    extraCommands: 
      - "mc anonymous set download provisioning/dremio"
      - "mc anonymous set download provisioning/warehouse"
      - "mc anonymous set download provisioning/upload"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: LoadBalancer
    loadBalancerIP: ""
    ports:
      api: 9000
  resources:
    requests:
      memory: "12Gi"
      cpu: "4"
    limits:
      memory: "24Gi"
      cpu: "8"
  persistence:
    storageClass: "gp2-expandable"
    size: 200Gi

zookeeper:
  enabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
  persistence:
    storageClass: "gp2-expandable"
    size: 20Gi
