global:
  defaultStorageClass: "gp2-expandable"

dremio:
  auth:
    enabled: true
    username: "admin"
    password: "Pa22word"
    firstName: "Josh"
    lastName: "Yorko"
    email: "joshua.yorko@gainwelltechnologies.com"

masterCoordinator:
  resources:
    requests:
      memory: "8Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "2"
  persistence:
    size: 8Gi
    storageClass: "gp2-expandable"
  extraStartParams: >-
    -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
    -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
  envVars:
    - name: DREMIO_TLS_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dremio-keystore-password
          key: password

coordinator:
  resources:
    requests:
      memory: "6Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "2"
  persistence:
    size: 16Gi
    storageClass: "gp2-expandable"
  extraStartParams: >-
    -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
    -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
  envVars:
    - name: DREMIO_TLS_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dremio-keystore-password
          key: password

executor:
  common:
    persistence:
      size: 20Gi
      storageClass: "gp2-expandable"
    resources:
      requests:
        cpu: "10"
        memory: "48Gi"
      limits:
        cpu: "12"
        memory: "56Gi"
    extraStartParams: >-
      -Xmx32g
      -XX:MaxDirectMemorySize=16g
      -XX:+UseG1GC
      -XX:G1HeapRegionSize=32M
      -XX:+UseGCOverheadLimit
      -XX:+ExplicitGCInvokesConcurrent
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/opt/dremio/data/heap-dump.hprof
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    envVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password



    autoscaling:
      hpa:
        enabled: true
        minReplicas: 5
        maxReplicas: 8
        targetCPU: 75
        targetMemory: 80

initContainers:
  - name: copy-default-conf
  - name: generate-conf
  - name: init-certs
  - name: set-keystore-permissions
    image: busybox
    command: ['sh', '-c', 'chown -R 1001:1001 /opt/dremio/tls && chmod -R 600 /opt/dremio/tls/*']
    volumeMounts:
      - name: dremio-tls
        mountPath: /opt/dremio/tls
  - name: setup-tls
    image: busybox
    command: ['sh', '-c', 'mkdir -p /opt/dremio/tls && cp /tls-secret/dremio.jks /opt/dremio/tls/dremio.jks && chmod 600 /opt/dremio/tls/dremio.jks && chown 1001:1001 /opt/dremio/tls/dremio.jks']
    volumeMounts:
      - name: dremio-tls
        mountPath: /tls-secret
      - name: tls-dir
        mountPath: /opt/dremio/tls

service:
  type: LoadBalancer

extraVolumes:
  - name: dremio-tls
    secret:
      secretName: dremio-tls-secret
  - name: tls-dir
    emptyDir: {}

extraVolumeMounts:
  - name: dremio-tls
    mountPath: /opt/dremio/tls
    readOnly: true
  - name: tls-dir
    mountPath: /opt/dremio/tls

extraEnvVars:
  - name: DREMIO_TLS_KEYSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dremio-keystore-password
        key: password

minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "Pa22word22"
  defaultBuckets: "dremio,warehouse,upload"
  provisioning:
    enabled: true
    extraCommands: 
      - "mc anonymous set download provisioning/dremio"
      - "mc anonymous set download provisioning/warehouse"
      - "mc anonymous set download provisioning/upload"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: LoadBalancer
    ports:
      api: 9000
  persistence:
    storageClass: "gp2-expandable"
    size: 100Gi

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    storageClass: "gp2-expandable"
    size: 8Gi
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
