apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook
  namespace: datalake
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

  storageClassName: "standard"
  hostPath:
    path: "/mnt/data/notebook"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-data
  namespace: datalake
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"
  volumeName: notebook
